# Generated by Django 4.2.5 on 2023-10-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='app_userpro_user_id_e70f3b_idx',
        ),
    ]
