# Generated by Django 4.2.6 on 2023-10-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userprofile_app_userpro_user_id_e70f3b_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='app_userpro_user_id_e70f3b_idx'),
        ),
    ]
