# Generated by Django 4.2.6 on 2023-10-06 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('TD', 'todo'), ('P', 'in-progress'), ('R', 'review'), ('C', 'complete')], default='TD', max_length=20)),
                ('rate_per_hour', models.CharField(default='$0', max_length=10)),
                ('time_needed', models.CharField(default='0hr', max_length=10)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
