# Generated by Django 4.2.6 on 2023-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='rate_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='time_needed',
            field=models.IntegerField(default=0),
        ),
    ]
