# Generated by Django 4.2.6 on 2023-10-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_taskmodel_task_taskmo_assigne_747969_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskmodel',
            index=models.Index(fields=['assigned_to', 'id', 'assigned_by'], name='task_taskmo_assigne_1feecd_idx'),
        ),
    ]
